<?php
defined('BASEPATH') or exit('No direct script access allowed');
?>
<!DOCTYPE html>
<html>
	<head>
		<title>Privacy Policy</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
		<link type="text/css" rel="stylesheet" href="<?php echo base_url() ?>assets/css/main.css">
		<link type="text/css" rel="stylesheet" href="<?php echo base_url() ?>assets/css/default.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	</head>
	<body>
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6 card card-body mt-4">
                <div class="card">
                    <div class="card-header">
                        PRIVACY POLICY
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">Purpose of the site</h5>
                        <p class="card-text"> The following statement explains Kasatria's Privacy Policy ("this Policy") regarding the personal information collected by Kasatria about you throughout the Website. Upon registration and from time to time, you will be asked to submit personal information about yourself (e.g name and email address etc.) in order to use the Website. By providing Kasatria with your details in the fields requested, you enable Kasatria to provide you with its services and its related channels. We will treat such personal information in accordance with this Policy. The Service is provided to you subject to Terms of Use & Notices and in accordance with the laws of Malaysia. Kasatria will act in accordance with current Malaysian legislation on personal information protection in this Policy and as far as practicable, aim to meet current Internet best practice.

The term Authorised Third Parties describes the contractors, agents and third party suppliers with whom Kasatria or other members of the Kasatria Group enter into agreements from time to time and persons with whom they may contract in order to provide the Kasatria Services.

For the purposes herein, all words and expressions shall have the same meaning as in the Kasatria Website Terms of Use & Notices, except where otherwise expressly stated. By submitting your information, you consent to the use of your personal information collected by us, in the manner as set out in this Policy.</p>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">For the purposes of this Privacy Policy:</h5>
                        <p class="card-text"> <b>Data Controller</b> , for the purposes of the GDPR (General Data Protection Regulation), refers to the Company as the legal person which alone or jointly with others determines the purposes and means of the processing of Personal Data</p>
                        <p class="card-text"> <b>Device</b>  means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
                        <p class="card-text"><b>Cookies</b>  are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
                        <p class="card-text"> <b>Personal Data</b>  is any information that relates to an identified or identifiable individual.</p>
                        <p class="card-text"> <b>Usage Data</b>  refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">Collecting and Using Your Personal Data</h5>
                        <p class="card-text"> <b>1.</b> First name </p>
                        <p class="card-text"> <b>2.</b> Age </p>
                        <p class="card-text"> <b>3.</b> Gender </p>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">USE OF YOUR PERSONAL INFORMATION</h5>
                        <p class="card-text"> Your personal information will be used by Kasatria, the Kasatria Group or Authorised Third Parties, in support of the purposes stated at the time at which it was given or sought, and/or for the following reasons:
                            For the purposes of technical administration of the Kasatria Website.
                            For research and development.
                            Statistical analysis.
                            Customer administration.
                            Profiling service preferences.
                            To detect and prevent fraudulent activity.
                            To support your questions about billing or use of the Kasatria Service.
                            In compliance with any regulatory, statutory or legal obligation imposed on us by any relevant authority.
                            Finance and marketing operations and activities and/or as required in the provision of our services including but not limited to credit control services.    
                        </div>
                    <div class="card-body">
                        <h5 class="card-title">CONTACTING THE GOOGLE ANALYTICS MALAYSIA WEBSITE</h5>
                        <p class="card-text">If you have any questions about this Policy or your dealings with the Kasatria Web site, please write to: <a href="admin@kasatria.com">admin@kasatria.com </a></div>
                </div>
            </div>
        </div>

	

		<!-- Import maps polyfill -->
		<!-- Remove this when import maps will be widely supported -->
        <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
		<script async src="https://unpkg.com/es-module-shims@1.3.6/dist/es-module-shims.js"></script>

		<script type="importmap">
			{
				"imports": {
					"three": "<?php echo base_url() ?>node_modules/three/build/three.module.js"
				}
			}
		</script>



		<script src='https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js'></script>


	</body>
</html>